GDHOTE.Hub.Mvc/Controllers/StateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GDHOTE.Hub.CoreObject.DataTransferObjects;
using GDHOTE.Hub.CoreObject.ViewModels;
using GDHOTE.Hub.PortalCore.Services;
using Newtonsoft.Json;

namespace GDHOTE.Hub.Mvc.Controllers
{
    public class StateController : BaseController
    {
        // GET: State
        public ActionResult Index()
        {
            var states = PortalStateService.GetAllStates(SetToken());
            return View("StateIndex", states);
        }
        public ActionResult New()
        {
            return View("StateForm", ReturnViewModel());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(CreateStateRequest createRequest)
        {
            if (!ModelState.IsValid)
            {
                return View("StateForm", ReturnViewModel());
            }
            var result = PortalStateService.CreateState(createRequest, SetToken());
            if (result != null)
            {
                //Successful
                if (result.ErrorCode == "00")
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ErrorBag = result.ErrorMessage;
                }

            }
            else
            {
                ViewBag.ErrorBag = "Unable to complete your request at the moment";
            }
            // If we got this far, something failed, redisplay form
            return View("StateForm", ReturnViewModel());
        }
        public ActionResult Edit(string id)
        {
            var state = PortalStateService.GetState(id, SetToken());
            var viewModelTemp = ReturnViewModel();
            var item = JsonConvert.SerializeObject(state);
            var viewModel = JsonConvert.DeserializeObject<StateFormViewModel>(item);
            viewModel.Countries = viewModelTemp.Countries;
            return View("StateForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteState(string id)
        {
            var result = PortalStateService.DeleteState(id, SetToken());
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        private StateFormViewModel ReturnViewModel()
        {
            var statuses = PortalStatusService.GetStatuses(SetToken());
            var countries = PortalCountryService.GetActiveCountries();
            var viewModel = new StateFormViewModel
            {
                Statuses = statuses,
                Countries = countries

            };
            return viewModel;
        }
    }
}

GDHOTE.Hub.Mvc/Views/State/Index.cshtml
@*@model List<GDHOTE.Hub.Core.Models.State>*@

@{
    ViewBag.Title = "States";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>States</h2>
<p>
    @Html.ActionLink("New State", "New", "State", null, new { @class = "result-list-button" })
</p>


@*@if (Model == null)
    {
        <p>No record(s) found</p>
    }
    else
    {

    }*@
<div>
    <table id="states" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Code</th>
                <th>Country Code</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @*@foreach (var state in Model)
                {
                    <tr>
                        <td>@Html.ActionLink(state.StateName, "Edit", "State", new { id = state.Id }, null)</td>
                        <td>@state.StateCode</td>
                        <td>@state.CountryCode</td>
                        <td><button data-state-id="@state.Id" class="btn btn-link js-delete">Delete</button></td>
                    </tr>
                }*@
        </tbody>
    </table>
</div>
@section scripts
{
    <script>
        $(document).ready(function () {
            var table = $("#states").DataTable({
                ajax: {
                    url: "/api/hub/state/getstates/",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "stateName",
                        render: function (data, type, state) {
                            return "<a href='/state/edit/" + state.id + "'>" + state.stateName + "</a>";
                        }
                    },
                    {
                        data: "stateCode"
                    },
                    {
                        data: "stateName"
                    },
                    {
                        data: "id",
                        render: function (data) {
                            return "<button class='btn btn-link js-delete' data-state-id=" + data + ">Delete</button>";
                        }
                    }
                ]
            });

            $("#states").on("click", ".js-delete", function () {
                var button = $(this);
                bootbox.confirm("Are you sure you want to proceed?", function (result) {
                    if (result) {
                        $.ajax({
                            //url: "/api/state" + button.attr("data-state-id"),
                            url: "/api/hub/state/deletestate?id=" + button.attr("data-state-id"),
                            method: "DELETE",
                            success: function () {
                                swal({
                                    title: "Success",
                                    text: "success",
                                    type: "success" 
                                });

                                table.row(button.parents("tr")).remove().draw();
                                //button.parents("tr").remove();
                            }
                        });
                    }
                });

            });
        });
    </script>
}

GDHOTE.Hub.Mvc/Views/State/StateForm.cshtml
@model GDHOTE.Hub.CoreObject.ViewModels.StateFormViewModel
@{
    ViewBag.Title = "New State";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var pagename = "";
    if (Model != null)
    {
        pagename = Model.Name == null ? "New State" : "Edit State";
    }

}
<h2>@pagename</h2>
@using (Html.BeginForm("Save", "State"))
{
    <div>
        <span class="text-danger">@ViewBag.ErrorBag</span>
        <div class="form-group">
            @Html.LabelFor(s => s.Name)
            @Html.TextBoxFor(s => s.Name, new { @class = "form-control gdhote-text-capitalize" })
            @Html.ValidationMessageFor(s => s.Name)
        </div>
        <div class="form-group">
            @Html.LabelFor(s => s.CountryId)
            @Html.DropDownListFor(s => s.CountryId, new SelectList(Model.Countries, "Id", "Name"), "Select Country", new { @class = "form-control" })
            @Html.ValidationMessageFor(s => s.CountryId)
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
        <div>
            @Html.AntiForgeryToken()
        </div>
    </div>

}

GDHOTE.Hub.Mvc/Views/State/StateIndex.cshtml
@model List<GDHOTE.Hub.CoreObject.ViewModels.StateViewModel>

@{
    ViewBag.Title = "States";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>States</h2>
<p>
    @Html.ActionLink("New State", "New", "State", null, new { @class = "result-list-button" })
</p>

@if (Model == null || Model.Count == 0)
{
    <p>No record(s) found</p>
}
else
{
    <div id="responsive">
        <div class="form-group">
            @Html.AntiForgeryToken()
        </div>

        <div>
            <table id="states" class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Country</th>
                        <th>Status</th>
                        <th>Date</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var state in Model)
                    {
                        <tr>
                            <td>@Html.ActionLink(state.Name, "Edit", "State", new { id = state.Id }, null)</td>
                            <td>@state.Country</td>
                            <td>@state.Status</td>
                            <td>@state.DateCreated.ToString("dd-MMM-yyyy")</td>
                            <td><button data-state-id="@state.Id" class="btn btn-link js-delete">Delete</button></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>

}
@section scripts
{
    <script>
        $(document).ready(function () {

            $("#states").on("click", ".js-delete", function () {
                var button = $(this);
                var id = button.attr("data-state-id");

                var form = $('#responsive');
                var token = $('input[name="__RequestVerificationToken"]', form).val();

                //Submit request
                var request = { __RequestVerificationToken: token };

                bootbox.confirm("Are you sure you want to proceed?", function (result) {
                    if (result) {
                        $.ajax({
                            url: '@Url.Action("DeleteState", "State")/' + id,
                            method: "POST",
                            data: request,
                            success: function (data) {
                                if (data !== null) {
                                    if (data.ErrorCode === "00") {
                                        swal({
                                            title: "Success",
                                            text: "success",
                                            type: "success"
                                        });

                                        window.location.reload(true);
                                    }
                                    else {
                                        alert(data.ErrorMessage);
                                    }
                                };

                            }
                        });
                    }
                });
            });
        });
    </script>
}