GDHOTE.Hub.Mvc/Models/AccountViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GDHOTE.Hub.Mvc.Models
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class ExternalLoginListViewModel
    {
        public string ReturnUrl { get; set; }
    }

    public class SendCodeViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
        public string ReturnUrl { get; set; }
        public bool RememberMe { get; set; }
    }

    public class VerifyCodeViewModel
    {
        [Required]
        public string Provider { get; set; }

        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }
        public string ReturnUrl { get; set; }

        [Display(Name = "Remember this browser?")]
        public bool RememberBrowser { get; set; }

        public bool RememberMe { get; set; }
    }

    public class ForgotViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class LoginViewModel
    {
        //[Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public string Code { get; set; }
    }

    public class ForgotPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

GDHOTE.Hub.Mvc/Controllers/MemberAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GDHOTE.Hub.CoreObject.DataTransferObjects;
using GDHOTE.Hub.CoreObject.ViewModels;
using GDHOTE.Hub.PortalCore.Services;
using Newtonsoft.Json;

namespace GDHOTE.Hub.Mvc.Controllers
{
    public class MemberAccountController : BaseController
    {
        // GET: MemberAccount
        public ActionResult Index()
        {
            var accounts = PortalAccountService.GetActiveAccounts(SetToken());
            return View("AccountIndex", accounts);
        }
        public ActionResult New()
        {
            var viewModel = ReturnViewModel();
            return View("AccountForm", viewModel);
        }
        public ActionResult Edit(string id)
        {
            var account = PortalAccountService.GetAccount(id, SetToken());
            var viewModelTemp = ReturnViewModel();
            var item = JsonConvert.SerializeObject(account);
            var viewModel = JsonConvert.DeserializeObject<AccountFormViewModel>(item);
            viewModel.AccountTypes = viewModelTemp.AccountTypes;
            return View("AccountForm", viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(CreateAccountRequest createRequest)
        {
            if (!ModelState.IsValid)
            {
                return View("AccountForm", ReturnViewModel());
            }
            var result = PortalAccountService.CreateAccount(createRequest, SetToken());
            if (result != null)
            {
                //Successful
                if (result.ErrorCode == "00")
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ErrorBag = result.ErrorMessage;
                }

            }
            else
            {
                ViewBag.ErrorBag = "Unable to complete your request at the moment";
            }
            // If we got this far, something failed, redisplay form
            return View("AccountForm", ReturnViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteAccount(string id)
        {
            var result = PortalAccountService.DeleteAccount(id, SetToken());
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        public ActionResult CreateInternalAccount()
        {
            var viewModel = ReturnInternalAccountViewModel();
            viewModel.AccountTypeId = (int)CoreObject.Enumerables.AccountType.InternalAccount;
            return View("CreateInternalAccount", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveInternalAccount(CreateInternalAccountRequest createRequest)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateInternalAccount", ReturnInternalAccountViewModel());
            }
            var result = PortalAccountService.CreateInternalAccount(createRequest, SetToken());
            if (result != null)
            {
                //Successful
                if (result.ErrorCode == "00")
                {
                    return RedirectToAction("InternalAccountList");
                }
                else
                {
                    ViewBag.ErrorBag = result.ErrorMessage;
                }
            }
            else
            {
                ViewBag.ErrorBag = "Unable to complete your request at the moment";
            }
            // If we got this far, something failed, redisplay form
            return View("CreateInternalAccount", ReturnInternalAccountViewModel());
        }
        public ActionResult InternalAccountList()
        {
            var accounts = PortalAccountService.GetAllInternalAccounts(SetToken());
            return View("InternalAccountList", accounts);
        }
        private AccountFormViewModel ReturnViewModel()
        {
            var accountTypes = PortalAccountTypeService.GetActiveAccountTypes(SetToken());
            var viewModel = new AccountFormViewModel
            {
                AccountTypes = accountTypes
            };
            return viewModel;
        }

        private InternalAccountFormViewModel ReturnInternalAccountViewModel()
        {
            var accountTypes = PortalAccountTypeService.GetActiveAccountTypes(SetToken());
            var banks = PortalBankService.GetActiveBanks(SetToken());
            var currencies = PortalCurrencyService.GetActiveCurrencies(SetToken());
            var viewModel = new InternalAccountFormViewModel
            {
                AccountTypes = accountTypes,
                Banks = banks,
                Currencies = currencies
            };
            return viewModel;
        }
    }
}

GDHOTE.Hub.Mvc/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GDHOTE.Hub.CoreObject.DataTransferObjects;
using GDHOTE.Hub.CoreObject.ViewModels;
using GDHOTE.Hub.PortalCore.Services;
using Newtonsoft.Json;

namespace GDHOTE.Hub.Mvc.Controllers
{
    public class MemberController : BaseController
    {
        // GET: Member
        public ActionResult Index()
        {
            //string criteria = "";
            //string startDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1).ToString("dd-MMM-yyyy");
            //string endDate = DateTime.Now.ToString("dd-MMM-yyyy");
            //var members = PortalMemberService.GetMembersByCriteria(criteria, startDate, endDate).ToList();

            //var members = PortalMemberService.GetRecentMembers(SetToken());
            return View();
        }
        public PartialViewResult GetRecentMembers(string id)
        {
            //string criteria = "";
            //string startDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1).ToString("dd-MMM-yyyy");
            //string endDate = DateTime.Now.ToString("dd-MMM-yyyy");
            //var members = PortalMemberService.GetMembersByCriteria(criteria, startDate, endDate).ToList();

            var member = PortalMemberService.GetRecentMembers(SetToken());
            return PartialView("_Index", member);
        }
        public PartialViewResult GetMemberByID(string id)
        {
            //string criteria = "";
            //string startDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1).ToString("dd-MMM-yyyy");
            //string endDate = DateTime.Now.ToString("dd-MMM-yyyy");
            //var members = PortalMemberService.GetMembersByCriteria(criteria, startDate, endDate).ToList();

            var member = PortalMemberService.GetMemberById(id,SetToken());
            return PartialView("_Index", member);
        }
        public ActionResult List()
        {
            string criteria = "";
            string startDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1).ToString("dd-MMM-yyyy");
            string endDate = DateTime.Now.ToString("dd-MMM-yyyy");
            var members = PortalMemberService.GetMembersByCriteria(criteria, startDate, endDate, SetToken());
            return View("ReadOnlyList", members);
        }
        public ActionResult New()
        {
            var viewModel = ReturnViewModel();
            return View("MemberForm", viewModel);
        }
        public ActionResult Edit(string id)
        {
            var member = PortalMemberService.GetMember(id, SetToken());
            var viewModelTemp = ReturnViewModel();
            var item = JsonConvert.SerializeObject(member);
            var viewModel = JsonConvert.DeserializeObject<UpdateMemberFormViewModel>(item);
            viewModel.Genders = viewModelTemp.Genders;
            viewModel.MaritalStatuses = viewModelTemp.MaritalStatuses;
            return View("UpdateMemberForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(CreateMemberRequest createRequest)
        {
            if (!ModelState.IsValid)
            {
                return View("MemberForm", ReturnViewModel());
            }
            var result = PortalMemberService.CreateMember(createRequest, SetToken());
            if (result != null)
            {
                //Successful
                if (result.ErrorCode == "00")
                {
                    return RedirectToAction("Index", "MemberDetails");
                }
                else
                {
                    ViewBag.ErrorBag = result.ErrorMessage;
                }
            }
            else
            {
                ViewBag.ErrorBag = "Unable to complete your request at the moment";
            }
            // If we got this far, something failed, redisplay form
            return View("MemberForm", ReturnViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(UpdateMemberRequest updateRequest)
        {
            if (!ModelState.IsValid)
            {
                return View("UpdateMemberForm");
            }
            var result = PortalMemberService.UpdateMember(updateRequest, SetToken());
            if (result != null)
            {
                //Successful
                if (result.ErrorCode == "00")
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ErrorBag = result.ErrorMessage;
                }
            }
            else
            {
                ViewBag.ErrorBag = "Unable to complete your request at the moment";
            }
            // If we got this far, something failed, redisplay form
            return View("UpdateMemberForm");
        }


        public ActionResult ApproveMember()
        {
            var members = PortalMemberService.GetPendingApproval(SetToken());
            return View(members);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ApproveMember(ApproveMemberRequest approveRequest)
        {
            if (!ModelState.IsValid)
            {
                return Json(ModelState);
            }
            var result = PortalMemberService.ApproveMember(approveRequest, SetToken());
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteMember(string id)
        {
            var result = PortalMemberService.DeleteMember(id, SetToken());
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UploadMember(UploadMemberRequest uploadRequest, HttpPostedFileBase uploadFile)
        {
            if (uploadFile == null)
            {
                ViewBag.ErrorBag = "Please specify a valid file";
            }
            else
            {
                uploadRequest.UploadFile = uploadFile.FileName;
                uploadRequest.UploadFileContent = new byte[uploadFile.ContentLength];
                uploadFile.InputStream.Read(uploadRequest.UploadFileContent, 0, uploadFile.ContentLength);
                uploadRequest.ChannelCode = (int)CoreObject.Enumerables.Channel.Web;
                var result = PortalMemberService.UploadMembers(uploadRequest, SetToken());
                if (result != null)
                {
                    ViewBag.ErrorBag = result.ErrorMessage;
                }
                else
                {
                    ViewBag.ErrorBag = "Unable to complete your request at the moment";
                }
            }
            // If we got this far, something failed, redisplay form
            return View();
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public JsonResult GetMember(string term)
        {
            var result = PortalMemberService.GetMembersByName(term, SetToken());
            var data = result.Select(r => new { value = r.MemberId, label = r.FirstName + " " + r.Surname }).ToList();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetMemberInfo()
        {
            return PartialView("_MemberInfo");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetMemberInfo(string id)
        {
            var result = PortalMemberService.GetMemberInformation(id, SetToken());
            return PartialView("_MemberInfo", result);
        }

        [HttpGet]
        public ActionResult GetUser(string searchTerm, int pageSize, int pageNum)
        {

            var member = PortalMemberService.SearchMember(searchTerm, SetToken());

            var data = member.Select(x => new { name = $"{x.Surname} {x.FirstName} {x.OtherNames} - {x.MobileNumber}", id = x.MemberId });
           

            var result = new
            {
                Total = data.Count(),
                Results = data.Skip((pageNum * pageSize) - 100).Take(pageSize)
            };

            return new JsonResult
            {
                Data = result,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };



        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult FetchReportByDate(string criteria, string startdate, string enddate)
        {
            var members = PortalMemberService.GetMembersByCriteria(criteria, startdate, enddate, SetToken());
            return PartialView("_MemberListReport", members);
        }

        private static MemberFormViewModel ReturnViewModel()
        {
            var genders = PortalGenderService.GetAllGenders();
            var maritalStatuses = PortalMaritalStatusService.GetAllMaritalStatuses();
            var viewModel = new MemberFormViewModel
            {
                Genders = genders,
                MaritalStatuses = maritalStatuses
            };
            return viewModel;
        }
    }
}

GDHOTE.Hub.Mvc/Views/MemberAccount/AccountForm.cshtml
@model GDHOTE.Hub.CoreObject.ViewModels.AccountFormViewModel
@{
    ViewBag.Title = "AccountForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var pagename = "";
    if (Model != null)
    {
        pagename = Model.MemberId == 0 ? "New Account" : "Edit Account";
    }

}
<h2>@pagename</h2>


@using (Html.BeginForm("Save", "MemberAccount"))
{
    <div>
        <span class="text-danger">@ViewBag.ErrorBag</span>
        <div class="form-group">
            @Html.LabelFor(a => a.AccountTypeId)
            @Html.DropDownListFor(a => a.AccountTypeId, new SelectList(Model.AccountTypes, "Id", "Name"), "Select Account Type", new { @class = "form-control" })
            @Html.ValidationMessageFor(a => a.AccountTypeId)
        </div>
        <div class="form-group">
            <label>Name</label>
            <div>
                <input id="membername" name="membername" required="" type="text" value="" class="form-control" />
                <input id="MemberId" name="MemberId" type="hidden" value="" class="form-control" />
                @Html.ValidationMessageFor(p => p.MemberId)
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(p => p.PaymentModeId)
                @Html.DropDownListFor(p => p.PaymentModeId, new SelectList(Model.ModeOfPayments, "Id", "Name"), "Select Mode Of Payment", new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.PaymentModeId)
            </div>
            <div class="form-group">
                @Html.LabelFor(p => p.CurrencyId)
                @Html.DropDownListFor(p => p.CurrencyId, new SelectList(Model.Currencies, "Id", "Name"), "Select Currency", new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.CurrencyId)
            </div>
            <div class="form-group">
                @Html.LabelFor(p => p.Amount)
                @Html.TextBoxFor(p => p.Amount, new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.Amount)
            </div>
            <div class="form-group">
                @Html.LabelFor(p => p.Narration)
                @Html.TextBoxFor(p => p.Narration, new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.Narration)
            </div>*@
        <div>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
        <div>@Html.AntiForgeryToken()</div>
    </div>

}


@section scripts
{
    <script>
        $(document).ready(function() {

            $("#membername").autocomplete({
                source: '@Url.Action("GetMember", "Member")',
                minLength: 5,
                select: function (event, ui) {
                    console.log(ui);
                    $(this).val(ui.item.value);
                    $(this).val(ui.item.label);
                    $("#MemberId").val(ui.item.value);
                    return false;
                },
                focus: function (event, ui) {
                    return false;
                }
            });


        });
    </script>
}

GDHOTE.Hub.Mvc/Views/MemberAccount/AccountIndex.cshtml
@model List<GDHOTE.Hub.CoreObject.ViewModels.AccountViewModel>

@{
    ViewBag.Title = "Accounts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Accounts</h2>
<p>
    @Html.ActionLink("New Account", "New", "MemberAccount", null, new { @class = "btn btn-primary" })
</p>


@if (Model == null || Model.Count == 0)
{
    <p>No record(s) found</p>
}
else
{
    <div id="responsive">
        <div class="form-group">
            @Html.AntiForgeryToken()
        </div>

        <div>
            <table id="accounts" class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Balance</th>
                        <th>Account Type</th>
                        <th>Status</th>
                        <th>Date</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var account in Model)
                    {
                        <tr>
                            <td>@Html.ActionLink(account.AccountName, "Edit", "MemberAccount", new { id = account.Id }, null)</td>
                            <td>@($"{account.Balance:#,##0.00}") </td>
                            <td>@account.AccountType</td>
                            <td>@account.Status</td>
                            <td>@account.DateCreated.ToString("dd-MMM-yyyy")</td>
                            <td><button data-account-id="@account.Id" class="btn btn-link js-delete">Delete</button></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>

}

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#accounts").DataTable();

            $("#accounts").on("click", ".js-delete", function () {
                var button = $(this);
                var id = button.attr("data-account-id");

                var form = $('#responsive');
                var token = $('input[name="__RequestVerificationToken"]', form).val();

                //Submit request
                var request = { __RequestVerificationToken: token };

                bootbox.confirm("Are you sure you want to proceed?", function (result) {
                    if (result) {
                        $.ajax({
                            url: '@Url.Action("DeleteAccount", "MemberAccount")/' + id,
                            method: "POST",
                            data: request,
                            success: function (data) {
                                if (data !== null) {
                                    if (data.ErrorCode === "00") {
                                        swal({
                                            title: "Success",
                                            text: "success",
                                            type: "success"
                                        });

                                        window.location.reload(true);
                                    }
                                    else {
                                        alert(data.ErrorMessage);
                                    }
                                };

                            }
                        });
                    }
                });

            });
        });
    </script>
}

GDHOTE.Hub.Mvc/Views/MemberAccount/CreateInternalAccount.cshtml
@model GDHOTE.Hub.CoreObject.ViewModels.InternalAccountFormViewModel
@{
    ViewBag.Title = "Create Account";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2>New Account</h2>


@using (Html.BeginForm("SaveInternalAccount", "MemberAccount"))
{
    <div>
        <span class="text-danger">@ViewBag.ErrorBag</span>
        <div class="form-group">
            @Html.LabelFor(a => a.BankId)
            @Html.DropDownListFor(a => a.BankId, new SelectList(Model.Banks, "Id", "Name"), "Select Bank", new { @class = "form-control" })
            @Html.ValidationMessageFor(a => a.BankId)
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.AccountNumber)
            @Html.TextBoxFor(a => a.AccountNumber, new { @class = "form-control gdhote-text-capitalize", autocomplete = "off" })
            @Html.ValidationMessageFor(a => a.AccountNumber)
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.AccountName)
            @Html.TextBoxFor(a => a.AccountName, new { @class = "form-control gdhote-text-capitalize", autocomplete = "off" })
            @Html.ValidationMessageFor(a => a.AccountName)
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.AccountTypeId)
            @Html.DropDownListFor(a => a.AccountTypeId, new SelectList(Model.AccountTypes, "Id", "Name"), "Select Type", new { @class = "form-control", disabled = "disabled" })
            @Html.ValidationMessageFor(a => a.AccountTypeId)
            @Html.HiddenFor(a => a.AccountTypeId)
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.CurrencyId)
            @Html.DropDownListFor(a => a.CurrencyId, new SelectList(Model.Currencies, "Id", "Name"), "Select Currency", new { @class = "form-control" })
            @Html.ValidationMessageFor(a => a.CurrencyId)
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
        <div>@Html.AntiForgeryToken()</div>
    </div>

}

GDHOTE.Hub.Mvc/Views/MemberAccount/InternalAccountList.cshtml
@model List<GDHOTE.Hub.CoreObject.ViewModels.AccountViewModel>

@{
    ViewBag.Title = "Accounts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Accounts</h2>
<p>
    @Html.ActionLink("New Account", "CreateInternalAccount", "MemberAccount", null, new { @class = "btn btn-primary" })
</p>


@if (Model == null || Model.Count == 0)
{
    <p>No record(s) found</p>
}
else
{
    <div id="responsive">
        <div class="form-group">
            @Html.AntiForgeryToken()
        </div>

        <div>
            <table id="accounts" class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>AccountNo</th>
                        <th>Name</th>
                        <th>Balance</th>
                        <th>Bank</th>
                        <th>Currency</th>
                        <th>Status</th>
                        <th>Date</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var account in Model)
                    {
                    <tr>
                        <td>@Html.ActionLink(account.AccountNumber, "Edit", "MemberAccount", new { id = account.Id }, null)</td>
                        <td>@account.AccountName</td>
                        <td>@($"{account.Balance:#,##0.00}") </td>
                        <td>@account.BankName</td>
                        <td>@account.Currency</td>
                        <td>@account.Status</td>
                        <td>@account.DateCreated.ToString("dd-MMM-yyyy")</td>
                        <td><button data-account-id="@account.Id" class="btn btn-link js-delete">Delete</button></td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>

}

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#accounts").DataTable();

            $("#accounts").on("click", ".js-delete", function () {
                var button = $(this);
                var id = button.attr("data-account-id");

                var form = $('#responsive');
                var token = $('input[name="__RequestVerificationToken"]', form).val();

                //Submit request
                var request = { __RequestVerificationToken: token };

                bootbox.confirm("Are you sure you want to proceed?", function (result) {
                    if (result) {
                        $.ajax({
                            url: '@Url.Action("DeleteAccount", "MemberAccount")/' + id,
                            method: "POST",
                            data: request,
                            success: function (data) {
                                if (data !== null) {
                                    if (data.ErrorCode === "00") {
                                        swal({
                                            title: "Success",
                                            text: "success",
                                            type: "success"
                                        });

                                        window.location.reload(true);
                                    }
                                    else {
                                        alert(data.ErrorMessage);
                                    }
                                };

                            }
                        });
                    }
                });

            });
        });
    </script>
}