GDHOTE.Hub.Mvc/Controllers/AccrualTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GDHOTE.Hub.CoreObject.DataTransferObjects;
using GDHOTE.Hub.CoreObject.Models;
using GDHOTE.Hub.CoreObject.ViewModels;
using GDHOTE.Hub.PortalCore.Services;
using Newtonsoft.Json;

namespace GDHOTE.Hub.Mvc.Controllers
{
    public class AccrualTypeController : BaseController
    {
        // GET: AccuralType
        public ActionResult Index()
        {
            var accrualTypes = PortalAccrualTypeService.GetAllAccrualTypes(SetToken());
            return View("AccrualIndex", accrualTypes);
        }
        public ActionResult New()
        {
            return View("AccrualTypeForm");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(CreateAccrualTypeRequest createRequest)
        {
            if (!ModelState.IsValid)
            {
                return View("AccrualTypeForm", createRequest);
            }
            var result = PortalAccrualTypeService.CreateAccrualType(createRequest, SetToken());
            if (result != null)
            {
                //Successful
                if (result.ErrorCode == "00")
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ErrorBag = result.ErrorMessage;
                }
            }
            else
            {
                ViewBag.ErrorBag = "Unable to complete your request at the moment";
            }
            // If we got this far, something failed, redisplay form
            return View("AccrualTypeForm", createRequest);
        }

        public ActionResult Edit(string id)
        {
            var accrualTypes = PortalAccrualTypeService.GetAccrualType(id, SetToken());
            var viewModelTemp = ReturnUpdateViewModel();
            var item = JsonConvert.SerializeObject(accrualTypes);
            var viewModel = JsonConvert.DeserializeObject<UpdateAccrualTypeFormViewModel>(item);
            viewModel.Statuses = viewModelTemp.Statuses;
            return View("UpdateAccrualTypeForm", viewModel);

        }

        public ActionResult Update(UpdateAccrualTypeRequest updateRequest)
        {
            if (!ModelState.IsValid)
            {
                return View("UpdateAccrualTypeForm", ReturnUpdateViewModel());
            }
            var result = PortalAccrualTypeService.UpdateAccrualType(updateRequest, SetToken());
            if (result != null)
            {
                //Successful
                if (result.ErrorCode == "00")
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ErrorBag = result.ErrorMessage;
                }
            }
            else
            {
                ViewBag.ErrorBag = "Unable to complete your request at the moment";
            }
            // If we got this far, something failed, redisplay form
            return View("UpdateAccrualTypeForm", ReturnUpdateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteAccrualType(string id)
        {
            var result = PortalAccrualTypeService.DeleteAccrualType(id, SetToken());
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        private UpdateAccrualTypeFormViewModel ReturnUpdateViewModel()
        {
            var statuses = PortalStatusService.GetStatuses(SetToken());
            var viewModel = new UpdateAccrualTypeFormViewModel
            {
                Statuses = statuses
            };
            return viewModel;
        }
    }
}

GDHOTE.Hub.Mvc/Views/AccrualType/AccrualIndex.cshtml
@model List<GDHOTE.Hub.CoreObject.ViewModels.AccrualTypeViewModel>

@{
    ViewBag.Title = "Accrual Types";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Accrual Types</h2>
<p>
    @Html.ActionLink("New Accrual Type", "New", "AccrualType", null, new { @class = "btn btn-primary" })
</p>


@if (Model == null || Model.Count == 0)
{
    <p>No record(s) found</p>
}
else
{
    <div id="responsive">
        <div class="form-group">
            @Html.AntiForgeryToken()
        </div>

        <div>
            <table id="activitytypes" class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Status</th>
                        <th>Date</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var actType in Model)
                    {
                        <tr>
                            <td>@Html.ActionLink(actType.Name, "Edit", "AccrualType", new { id = actType.Id }, null)</td>
                            <td>@actType.Status</td>
                            <td>@actType.DateCreated.ToString("dd-MMM-yyyy")</td>
                            <td><button data-AccrualType-id="@actType.Id" class="btn btn-link js-delete">Delete</button></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>

}
@section scripts
{
    <script>
        $(document).ready(function () {
            $("#activitytypes").DataTable();

            $("#activitytypes").on("click", ".js-delete", function () {
                var button = $(this);
                var id = button.attr("data-AccrualType-id");

                var form = $('#responsive');
                var token = $('input[name="__RequestVerificationToken"]', form).val();

                //Submit request
                var request = { __RequestVerificationToken: token };

                bootbox.confirm("Are you sure you want to proceed?", function (result) {
                    if (result) {
                        $.ajax({
                            url: '@Url.Action("DeleteAccrualType", "AccrualType")/' + id,
                            method: "POST",
                            data: request,
                            success: function (data) {
                                if (data !== null) {
                                    if (data.ErrorCode === "00") {
                                        swal({
                                            title: "Success",
                                            text: "success",
                                            type: "success"
                                        });

                                        window.location.reload(true);
                                    }
                                    else {
                                        alert(data.ErrorMessage);
                                    }
                                };

                            }
                        });
                    }
                });

            });
        });
    </script>
}

GDHOTE.Hub.Mvc/Views/AccrualType/AccrualTypeForm.cshtml
@model  GDHOTE.Hub.CoreObject.DataTransferObjects.CreateAccrualTypeRequest
    @{
        ViewBag.Title = "Accrual Type Form";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    @{
        var pagename = "";
        if (Model != null)
        {
            pagename = Model.Name == null ? "New Accrual Type" : "Edit Accrual Type";
        }

    }
    <h2>@pagename</h2>
    @using (Html.BeginForm("Save", "AccrualType"))
    {
        <div>
            <span class="text-danger">@ViewBag.ErrorBag</span>
            <div class="form-group">
                @Html.LabelFor(c => c.Name)
                @Html.TextBoxFor(c => c.Name, new { @class = "form-control gdhote-text-capitalize", autocomplete = "off" })
                @Html.ValidationMessageFor(c => c.Name)
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
            <div class="form-group">
                @Html.AntiForgeryToken()
            </div>
        </div>

    }

GDHOTE.Hub.Mvc/Views/AccrualType/UpdateAccrualTypeForm.cshtml
@model  GDHOTE.Hub.CoreObject.ViewModels.UpdateAccrualTypeFormViewModel
    @{
        ViewBag.Title = "Update Accrual Type";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    @{
        var pagename = "";
        if (Model != null)
        {
            pagename = Model.Name == null ? "New Accrual Type" : "Edit Accrual Type";
        }

    }
    <h2>@pagename</h2>
    @using (Html.BeginForm("Update", "AccrualType"))
    {
        <div>
            <span class="text-danger">@ViewBag.ErrorBag</span>
            <div class="form-group">
                @Html.LabelFor(c => c.Name)
                @Html.TextBoxFor(c => c.Name, new { @class = "form-control gdhote-text-capitalize", autocomplete = "off" })
                @Html.ValidationMessageFor(c => c.Name)
            </div>
            <div class="form-group">
                @Html.LabelFor(a => a.StatusId)
                @Html.DropDownListFor(a => a.StatusId, new SelectList(Model.Statuses, "Id", "Name"), "Select Status", new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.StatusId)
            </div>
            <div>@Html.HiddenFor(a => a.Id)</div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
            <div class="form-group">
                @Html.AntiForgeryToken()
            </div>
        </div>

    }